name: automate
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
  - pyg
dependencies:
  - python
  - cudatoolkit
  - pytorch>=1.10
  - pyg
  - numpy
  - pandas
  - pytorch-lightning
  - tensorboard
  - pyarrow
  - requests
  - scipy
  - matplotlib
  - dotmap
